---
title: "Mercado de trabalho na mineração 2017 à 2019: Estoques com dados da RAIS"
output: 
  html_document: 
    theme: journal
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(kableExtra)
options(knitr.kable.NA = ' . ')
```

```{r carregamento, include=FALSE}

# RAIS 2010 - 2019 ----
RAIS_2010_2019_VINC <- 
  readRDS('D:/Users/humberto.serna/Documents/D_Lake/RAIS_CAGED/RAIS_2010_2019_VINC.Rda')

# CNAE 2.3 ----
source('D:/Users/humberto.serna/Documents/D_Lake/CNAE.R')

# CUIDADO ! ATENÇÃO! OS MICRODADOS ESTÃO COM SUBCLASSE SEM '0' NA FRENTE. HÁ SUBCLASSES COM 7 E OUTRAS COM 6 DÍGITOS....
# ______________________________________________________________________________________________----
```

```{r Delimitação Geo-Tempo, include=FALSE}

RAIS_2010_2019_VINC <- 
  RAIS_2010_2019_VINC[RAIS_2010_2019_VINC$ano >= 2017,]


RAIS_2010_2019_VINC <- 
  RAIS_2010_2019_VINC[RAIS_2010_2019_VINC$UF_Trab %in% c("AC","AM", "AP", "TO", "RO", "PA", "RR"),]


```




```{r EXTRATIVA MINERAL: subclasses alvo, include=FALSE}

# _____ lista subclasses_alvo na seção B (Extrativa Mineral - Exceto petróleo & Gás) ----
subclasses_alvo_SECAO_B <-                    
    c(#subclasse  denominação
       "500301",	#Extração de carvão mineral
       "500302",	#Beneficiamento de carvão mineral
       "710301",	#Extração de minério de ferro
       "710302",	#Pelotização, sinterização e outros beneficiamentos de minério de ferro
       "721901",	#Extração de minério de alumínio
       "721902",	#Beneficiamento de minério de alumínio
       "722701",	#Extração de minério de estanho
       "722702",	#Beneficiamento de minério de estanho
       "723501",	#Extração de minério de manganês
       "723502",	#Beneficiamento de minério de manganês
       "724301",	#Extração de minério de metais preciosos
       "724302",	#Beneficiamento de minério de metais preciosos
       "725100",	#Extração de minerais radioativos
       "729401",	#Extração de minérios de nióbio e titânio
       "729402",	#Extração de minério de tungstênio
       "729403",	#Extração de minério de níquel
       "729404",	#Extração de minérios de cobre, chumbo, zinco e outros minerais metálicos não ferrosos não especificados anteriormente
       "729405",	#Beneficiamento de minérios de cobre, chumbo, zinco e outros minerais metálicos não ferrosos não especificados anteriormente
       "810001",	#Extração de ardósia e beneficiamento associado
       "810002",	#Extração de granito e beneficiamento associado
       "810003",	#Extração de mármore e beneficiamento associado
       "810004",	#Extração de calcário e dolomita e beneficiamento associado
       "810005",	#Extração de gesso e caulim
       "810006",	#Extração de areia, cascalho ou pedregulho e beneficiamento associado
       "810007",	#Extração de argila e beneficiamento associado
       "810008",	#Extração de saibro e beneficiamento associado
       "810009",	#Extração de basalto e beneficiamento associado
       "810010",	#Beneficiamento de gesso e caulim associado à extração
       "810099",	#Extração e britamento de pedras e outros materiais para construção e beneficiamento associado
       "891600",	#Extração de minerais para fabricação de adubos, fertilizantes e outros produtos químicos
       "892401",	#Extração de sal marinho
       "892402",	#Extração de salgema
       "892403",	#Refino e outros tratamentos do sal
       "893200",	#Extração de gemas (pedras preciosas e semipreciosas)
       "899101",	#Extração de grafita
       "899102",	#Extração de quartzo
       "899103",	#Extração de amianto
       "899199",	#Extração de outros minerais não metálicos não especificados anteriormente
       "990401",	#Atividades de apoio à extração de minério de ferro
       "990402",	#Atividades de apoio à extração de minerais metálicos não ferrosos
       "990403"	  #Atividades de apoio à extração de minerais não metálicos
  )

# _____ delimitando df por subclasses alvo
    df_Extrativa <- RAIS_2010_2019_VINC[RAIS_2010_2019_VINC$`CNAE 2.0 Subclasse` %in% subclasses_alvo_SECAO_B, ]
    
```

***
<br>
<br>

<div style="text-align:center">

### Extração Mineral

</div>

```{r Extrativa_UF_Subclasse_Ano, echo=FALSE, message=FALSE}

df_Extrativa_UF_Subclasse_Ano <-
  summarise(
      group_by(
        df_Extrativa[df_Extrativa$ano %in% c(2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019),], 
        UF_Trab, ano),
      "Estoque" = sum(`Vínculo Ativo 31/12`, na.rm = TRUE)
      )

kable(
  spread(df_Extrativa_UF_Subclasse_Ano, key = ano, value = Estoque), caption = "Quantidade de trabalhadores na Extrativa Mineral (Seção B da CNAE) por UF e Ano", allign = "c") %>% kable_styling(bootstrap_options = "striped", full_width = FALSE)

```

<br><br><br>

```{r Extrativa_Município_Subclasse_Trimestre, eval=FALSE, message=FALSE, include=FALSE}

df_Extrativa_Municipio_Subclasse_Ano <-
  summarise(
    group_by(df_Extrativa[df_Extrativa$ano %in% c(2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019), ],
             Mun_Trab, UF_Trab, ano),
    "Estoque" = sum(`Vínculo Ativo 31/12`, na.rm = TRUE)
  )

kable(head(arrange(
  spread(
    df_Extrativa_Municipio_Subclasse_Ano,
    key = ano,
    value = Estoque
  ),
  desc(`2019`)
), 20), caption = "Quantidade de trabalhadores na Extrativa Mineral (Seção B da CNAE) por Município e ano", allign = "c") %>% kable_styling(bootstrap_options = "striped", full_width = FALSE)

```


```{r INDÚSTRIA DE TRANSFORMAÇÃO (MINERAL): subclasses alvo, include=FALSE}

 # _____ Lista classes Alvo na Seção C (Indústria de Transformação Relacionada não associada/consecutiva à mineração) ----
 
 classes_alvo_SECAO_C <- 
   c(
      "20126",	  #    Fabricação de Intermediários para Fertilizantes 
      "20134",    #    Fabricação de Adubos e Fertilizantes 
      "23206",    #    Fabricação de Cimento 
      "23303",    #    Fabricação de Artefatos de Concreto, Cimento, Fibrocimento, Gesso e Materiais Semelhantes 
      "23419",    #    Fabricação de Produtos Cerâmicos Refratários 
      "23427",    #    Fabricação de Produtos Cerâmicos NãoRefratários para Uso Estrutural na Construção 
      "23494",    #    Fabricação de Produtos Cerâmicos NãoRefratários não Especificados Anteriormente 
      "23915",    #    Aparelhamento e Outros Trabalhos em Pedras 
      "23923",    #    Fabricação de Cal e Gesso 
      "23991",    #    Fabricação de Produtos de Minerais NãoMetálicos não Especificados Anteriormente 
      "24113",    #    Produção de FerroGusa 
      "24121",    #    Produção de Ferroligas 
      "24211",    #    Produção de SemiAcabados de Aço 
      "24229",    #    Produção de Laminados Planos de Aço 
      "24237",    #    Produção de Laminados Longos de Aço 
      "24245",    #    Produção de Relaminados, Trefilados e Perfilados de Aço 
      "24318",    #    Produção de Tubos de Aço com Costura 
      "24393",    #    Produção de Outros Tubos de Ferro e Aço 
      "24415",    #    Metalurgia do Alumínio e Suas Ligas 
      "24423",    #    Metalurgia dos Metais Preciosos 
      "24431",    #    Metalurgia do Cobre 
      "24491",    #    Metalurgia dos Metais NãoFerrosos e Suas Ligas não Especificados Anteriormente 
      "24512",    #    Fundição de Ferro e Aço 
      "25314",    #    Produção de forjados de aço e de metais nãoferrosos e suas ligas 
      "24521",    #    Fundição de Metais NãoFerrosos e Suas Ligas 
      "32116")    #    Lapidação de Gemas e Fabricação de Artefatos de Ourivesaria e Joalheria 
 
 
 # __________ SUBCLASSES alvo na Seção C ----
  subclasses_alvo_SECAO_C <- 
   cnae[cnae$classe %in% classes_alvo_SECAO_C & cnae$subclasse != 0, c("subclasse")]

# _____ delimitando df por subclasses alvo
  df_Transformação <- RAIS_2010_2019_VINC[RAIS_2010_2019_VINC$`CNAE 2.0 Subclasse` %in% subclasses_alvo_SECAO_C, ]
  
```

<br><br><br>

<div style="text-align:center">

### Indústria de Transformação Mineral

</div>

```{r Transformação_UF_Subclasse_Ano, echo=FALSE, message=FALSE}

df_Transformação_UF_Subclasse_Ano <-
  summarise(
      group_by(
        df_Transformação[df_Transformação$ano %in% c(2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019),], 
        UF_Trab, ano),
      "Estoque" = sum(`Vínculo Ativo 31/12`, na.rm = TRUE)
      )

kable(
  spread(df_Transformação_UF_Subclasse_Ano, key = ano, value = Estoque), caption = "Quantidade de trabalhadores na Transformação Mineral (Seção C da CNAE) por UF e Ano", allign = "c") %>% kable_styling(bootstrap_options = "striped", full_width = FALSE)

```

<br><br><br>


```{r Transformação_Município_Subclasse_Trimestre, eval=FALSE, message=FALSE, include=FALSE}

df_Transformação_Municipio_Subclasse_Ano <-
  summarise(
    group_by(df_Transformação[df_Transformação$ano %in% c(2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019), ],
             Mun_Trab, UF_Trab, ano),
    "Estoque" = sum(`Vínculo Ativo 31/12`, na.rm = TRUE)
  )

kable(head(arrange(
  spread(
    df_Transformação_Municipio_Subclasse_Ano,
    key = ano,
    value = Estoque
  ),
  desc(`2019`)
), 30), caption = "Quantidade de trabalhadores na Transformação Mineral (Seção C da CNAE) Município e Ano", allign = "c") %>% kable_styling(bootstrap_options = "striped", full_width = FALSE)

```


